
CONNECTION_STRING = "mongodb+srv://root:root@cluster0.dx6xp.mongodb.net/test"

# &&&&&&&& GENERATION CONSTANTS &&&&&&&&

NUM_DOCTORS = 7
NUM_NURSES = 7
NUM_PLACES = 6
NUM_PEOPLE = 20

MIN_V = 0  # MIN NUMBER OF VACCINES PER PERSON
MAX_V = 3  # MAX NUMBER OF VACCINES PER PERSON

MIN_T = 1  # MIN NUMBER OF TESTS PER PERSON
MAX_T = 3  # MAX NUMBER OF TESTS PER PERSON

POSITIVE_PROBABILITY = 0.02
